#!/bin/bash
#SBATCH --job-name=inference
#SBATCH --time=2-00:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=96
#SBATCH --gres=gpu:pvc:4
#SBATCH --nodes=1
#SBATCH --partition=staff
#SBATCH --mem=488G
#SBATCH --output=out
#SBATCH --exclusive
module purge
module load WebProxy 
# ADD YOUR COMMANDS BELOW
#ip addr | grep inet
export CLUSTER=ACES
export NUM_GPUS=4
cd /scratch/user/u.ks124812/dor-hprc-interactive-llm/
source modules.sh
source venv/bin/activate
cd inference
bash run_script.sh
