#!/bin/bash
#SBATCH --job-name=inference
#SBATCH --time=7-00:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=192
#SBATCH --gres=gpu:a30:2
#SBATCH --nodes=1
#SBATCH --partition=staff
#SBATCH --mem=370G
#SBATCH --output=out
#SBATCH --error=error
#SBATCH --nodelist=lg09

module purge
module load WebProxy 

export CLUSTER=LAUNCH
# ADD YOUR COMMANDS BELOW
ip addr | grep inet
cd /sw/hprc/sw/dor-hprc-interactive-llm
source modules.sh
source venv/bin/activate
cd inference
python3 app.py

