#!/bin/bash
#SBATCH --job-name=inference
#SBATCH --time=28-00:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --gres=gpu:pvc:4
#SBATCH --nodes=1
#SBATCH --qos=hprc
#SBATCH --reservation=pvc_llm
#SBATCH --mem=488G
#SBATCH --partition=staff
#SBATCH --output=out
#SBATCH --nodelist=ac028
module purge
module load WebProxy 
cd /sw/hprc/sw/dor-hprc-interactive-llm/
source modules.sh
source venv/bin/activate
cd inference
# ADD YOUR COMMANDS BELOW
#ip addr | grep inet
export CLUSTER=ACES
export NUM_GPUS=4
export NUM_NODES=1
export P_PER_NODE=1
for(( i=0;i<NUM_NODES;i++ )); do
  for(( j=0; j<P_PER_NODE; j++ )); do
    port=$((1000+j))
    log_prefix="logs/node_${i}_proc_${j}_port_${port}"
    stdout_file="${log_prefix}.out"
    stderr_file="${log_prefix}.err"
    python3 app.py "${port}" > "${stdout_file}" 2>&1 &
  done
done
wait
