#!/bin/bash
#SBATCH --job-name=inference_test
#SBATCH --time=2-00:00:00
#SBATCH --ntasks=3
#SBATCH --cpus-per-task=12
#SBATCH --gres=gpu:pvc:4
#SBATCH --nodes=1
#SBATCH --mem=488G
#SBATCH --partition=staff
#SBATCH --reservation=pvc_llm
#SBATCH --output=out2
#SBATCH --nodelist=ac025
#SBATCH --exclusive
module purge
module load WebProxy 
cd /sw/hprc/sw/dor-hprc-interactive-llm/
source modules.sh
source venv/bin/activate
cd inference
# ADD YOUR COMMANDS BELOW
#ip addr | grep inet
export CLUSTER=ACES
export NUM_GPUS=4
python3 inference_script.py
wait
