#!/bin/bash
#SBATCH --job-name=inference_master
#SBATCH --time=28-00:00:00
#SBATCH --ntasks=3
#SBATCH --cpus-per-task=12
#SBATCH --gres=gpu:pvc:4
#SBATCH --nodes=1
#SBATCH --qos=hprc
#SBATCH --reservation=pvc_llm
#SBATCH --mem=488G
#SBATCH --partition=staff
#SBATCH --output=out
#SBATCH --exclusive
module purge
module load WebProxy 
cd /sw/hprc/sw/dor-hprc-interactive-llm/
source modules.sh
source venv/bin/activate
cd inference
# ADD YOUR COMMANDS BELOW
#ip addr | grep inet
export CLUSTER=ACES
export NUM_GPUS=4
python3 master_app.py $NUM_CHILDREN &
python3 app.py 1025 > "logs/ac028" 2>&1 &
wait
